services:
    # Controllers
    arkon.user.list_users_controller:
        class: Arkon\Bundle\ApiBundle\Controller\ListUsersController
        arguments:
            - @arkon.user.list_users
            - @form.factory

    arkon.user.get_user_controller:
        class: Arkon\Bundle\ApiBundle\Controller\GetUserController
        arguments:
            - @arkon.user.get_user

    arkon.user.create_user_controller:
        class: Arkon\Bundle\ApiBundle\Controller\CreateUserController
        arguments:
            - @arkon.user.create_user
            - @form.factory
            - @router

    arkon.user.edit_user_controller:
        class: Arkon\Bundle\ApiBundle\Controller\EditUserController
        arguments:
            - @arkon.user.edit_user
            - @form.factory

    arkon.user.remove_user_controller:
        class: Arkon\Bundle\ApiBundle\Controller\RemoveUserController
        arguments:
            - @arkon.user.remove_user