language: php

env:
  - SYMFONY_DEPRECATIONS_HELPER=weak

php:
  - 5.6
  - 7.0
  - nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - cp app/phpunit.xml.dist app/phpunit.xml

script:
  - phpunit --configuration app/phpunit.xml

after_script:
  - bin/coveralls -v -c .coveralls.yml
