language: php

env:
- SYMFONY_DEPRECATIONS_HELPER=weak

php:
  - 5.6
  - 7.0
  - nightly

before_script:
  - composer install
  - cp app/phpunit.xml.dist app/phpunit.xml

script: phpunit --configuration app/phpunit.xml
