language: php

env:
  - SYMFONY_DEPRECATIONS_HELPER=weak

php:
  - 5.6
  - 7.0
  - nightly

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - cp app/phpunit.xml.dist app/phpunit.xml

script:
  - phpunit --configuration app/phpunit.xml

after_script:
  - bin/coveralls -v -c .coveralls.yml
