arkon_user_listUsers:
    path: /users
    defaults: { _controller: arkon.user.list_users_controller:listUsersAction }
    requirements:
        _method: GET

arkon_user_getUser:
    path: /users/{id}
    defaults: { _controller: arkon.user.get_user_controller:getUserAction }
    requirements:
        id: \d+
        _method: GET

arkon_user_createUser:
    path: /users
    defaults: { _controller: arkon.user.create_user_controller:createUserAction }
    requirements:
        _method: POST

arkon_user_editUser:
    path: /users/{id}
    defaults: { _controller: arkon.user.edit_user_controller:editUserAction }
    requirements:
        _method: PUT
        id: \d+