services:
    arkon.user.list_users_controller:
        class: Arkon\Bundle\UserBundle\Controller\ListUsersController
        arguments:
            - @arkon.user.user_repository_db
            - @templating

    arkon.user.user_repository_db:
        class:           Arkon\Bundle\UserBundle\Repository\DbUserRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:
            - ArkonUserBundle:User