services:
    # Controllers
    arkon.user.list_users_controller:
        class: Arkon\Bundle\UserBundle\Controller\ListUsersController
        arguments:
            - @arkon.user.list_users
            - @form.factory

    arkon.user.get_user_controller:
        class: Arkon\Bundle\UserBundle\Controller\GetUserController
        arguments:
            - @arkon.user.get_user

    arkon.user.create_user_controller:
        class: Arkon\Bundle\UserBundle\Controller\CreateUserController
        arguments:
            - @arkon.user.create_user
            - @form.factory
            - @router

    arkon.user.edit_user_controller:
        class: Arkon\Bundle\UserBundle\Controller\EditUserController
        arguments:
            - @arkon.user.edit_user
            - @form.factory

    arkon.user.remove_user_controller:
        class: Arkon\Bundle\UserBundle\Controller\RemoveUserController
        arguments:
            - @arkon.user.remove_user

    # Forms:
    arkon.user.edit_user_form:
        class: Arkon\Bundle\UserBundle\Form\EditUserType
        tags:
            - { name: form.type, alias: user_edit }

    arkon.user.create_user_form:
        class: Arkon\Bundle\UserBundle\Form\CreateUserType
        tags:
            - { name: form.type, alias: user_create }

    arkon.user.search_users_form:
        class: Arkon\Bundle\UserBundle\Form\SearchUsersType
        tags:
            - { name: form.type, alias: user_search }

    # Services
    arkon.user.user_repository_db:
        class: Arkon\Bundle\UserBundle\Repository\DbUserRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - ArkonUserBundle:User

    # Use cases
    arkon.user.list_users:
        class: Arkon\Bundle\UserBundle\UseCase\ListUsers
        arguments:
            - @arkon.user.user_repository_db

    arkon.user.get_user:
        class: Arkon\Bundle\UserBundle\UseCase\GetUser
        arguments:
            - @arkon.user.user_repository_db

    arkon.user.create_user:
        class: Arkon\Bundle\UserBundle\UseCase\CreateUser
        arguments:
            - @arkon.user.user_repository_db
            - @validator

    arkon.user.edit_user:
        class: Arkon\Bundle\UserBundle\UseCase\EditUser
        arguments:
            - @arkon.user.user_repository_db
            - @validator

    arkon.user.remove_user:
        class: Arkon\Bundle\UserBundle\UseCase\RemoveUser
        arguments:
            - @arkon.user.user_repository_db