arkon_phonebook_add_number:
    path: /users/{id}/numbers
    defaults: { _controller: arkon.phonebook.add_number_controller:addNumberAction }
    requirements:
        id: \d+
        _method: POST

arkon_phonebook_get_user_numbers:
    path: /users/{id}/numbers
    defaults: { _controller: arkon.phonebook.get_user_numbers_controller:getUserNumbersAction }
    requirements:
        id: \d+
        _method: GET

arkon_phonebook_get_user_number:
    path: /users/{id}/numbers/{numberId}
    defaults: { _controller: arkon.phonebook.get_user_number_controller:getUserNumberAction }
    requirements:
        id: \d+
        numberId: \d+
        _method: GET

arkon_phonebook_edit_number:
    path: /users/{id}/numbers/{numberId}
    defaults: { _controller: arkon.phonebook.edit_number_controller:editPhoneNumberAction }
    requirements:
        id: \d+
        numberId: \d+
        _method: PUT
